version: '3'

services:
  app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: sennder_service
    volumes:
      - .:/sennder_service
    ports:
      - "8000:8000"
  redis:
    image: redis:latest
    depends_on:
      - app
    ports:
        - 6379:6379
    volumes:
        - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]